server:
  port: 8081

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/team_gof
#    url: jdbc:postgresql://194.163.158.136:5432/team_gof
    username: user
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    showSql: true
    generateDdl: false
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddlAuto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        defaultSchema: ${DATASOURCE_DEFAULT_SCHEMA:gof_team}
#        defaultCatalog: ${DATASOURCE_DEFAULT_SCHEMA:gof_team}

  flyway:
    baselineOnMigrate: true
    schemas: ${DATASOURCE_DEFAULT_SCHEMA:gof_team}
    outOfOrder: true