CREATE TABLE IF NOT EXISTS help_file
(
    help_file_id       BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    url                VARCHAR(2500),
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_helpfile PRIMARY KEY (help_file_id)
);
ALTER TABLE IF EXISTS help_file
    ADD CONSTRAINT url_help_file_uc UNIQUE (url);

CREATE TABLE IF NOT EXISTS epreuve_help_file
(
    epreuve_help_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    help_file_id         BIGINT                                    NOT NULL,
    epreuve_id           BIGINT                                    NOT NULL,
    created_by           VARCHAR(255),
    created_date         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by     VARCHAR(255),
    CONSTRAINT pk_epreuve_help_file PRIMARY KEY (epreuve_help_file_id)
);
ALTER TABLE IF EXISTS epreuve_help_file
    ADD CONSTRAINT url_epreuve_help_file_uc UNIQUE (help_file_id, epreuve_id);

ALTER TABLE IF EXISTS epreuve_help_file
    ADD CONSTRAINT FK_EPREUVE_HELP_FILE_ON_EPREUVE FOREIGN KEY (epreuve_id) REFERENCES epreuve (epreuve_id);

ALTER TABLE IF EXISTS epreuve_help_file
    ADD CONSTRAINT FK_EPREUVE_HELP_FILE_ON_HELP_FILE FOREIGN KEY (help_file_id) REFERENCES help_file (help_file_id);