CREATE TABLE precision
(
    precision_id       BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    epreuve_id         BIGINT                                    NOT NULL,
    minimal_conditions JSONB                                     NOT NULL,
    other_rules        JSONB                                     NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_precision PRIMARY KEY (precision_id)
);

ALTER TABLE IF EXISTS precision
    ADD CONSTRAINT uc_precision_epreuve UNIQUE (epreuve_id);

ALTER TABLE IF EXISTS precision
    ADD CONSTRAINT FK_PRECISION_ON_EPREUVE FOREIGN KEY (epreuve_id) REFERENCES epreuve (epreuve_id);