CREATE TABLE IF NOT EXISTS exclusion
(
    exclusion_id       BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    label              VARCHAR,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_exclusion PRIMARY KEY (exclusion_id)
);

CREATE TABLE IF NOT EXISTS epreuve_exclusion
(
    epreuve_exclusion_id BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    exclusion_id         BIGINT                                    NOT NULL,
    epreuve_id           BIGINT                                    NOT NULL,
    created_by           VARCHAR(255),
    created_date         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by     VARCHAR(255),
    CONSTRAINT pk_epreuve_exclusion PRIMARY KEY (epreuve_exclusion_id)
);

ALTER TABLE IF EXISTS epreuve_exclusion
    ADD CONSTRAINT url_epreuve_exclusion_uc UNIQUE (exclusion_id, epreuve_id);

ALTER TABLE IF EXISTS epreuve_exclusion
    ADD CONSTRAINT FK_EPREUVE_EXCLUSION_ON_EPREUVE FOREIGN KEY (epreuve_id) REFERENCES epreuve (epreuve_id);

ALTER TABLE IF EXISTS epreuve_exclusion
    ADD CONSTRAINT FK_EPREUVE_EXCLUSION_ON_EXCLUSION FOREIGN KEY (exclusion_id) REFERENCES exclusion (exclusion_id);