ALTER TABLE IF EXISTS team
    ADD COLUMN IF NOT EXISTS departement VARCHAR(255)  NOT NULL,
    ADD COLUMN IF NOT EXISTS description VARCHAR(5000) NOT NULL,
    ADD COLUMN IF NOT EXISTS members     JSONB;
