CREATE TABLE IF NOT EXISTS team_gof_admin
(
    team_gof_admin_id  BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    email              VARCHAR(255)                              NOT NULL,
    pwd                VARCHAR(255)                              NOT NULL,
    role               VARCHAR(255),
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_team_gof_admin PRIMARY KEY (team_gof_admin_id)
);

ALTER TABLE team_gof_admin
    ADD CONSTRAINT uc_team_gof_admin_email UNIQUE (email);