CREATE TABLE IF NOT EXISTS "user"
(
    user_id            BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    email              VARCHAR(255)                              NOT NULL,
    pwd                VARCHAR(255)                              NOT NULL,
    created_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    last_modified_by   VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (user_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);